#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService_ASM_TungBT
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.Runtime.Serialization;
	using System.ComponentModel;
	using System;
	
	
	public partial class ServiceDatabaseDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKhachHang(KhachHang instance);
    partial void UpdateKhachHang(KhachHang instance);
    partial void DeleteKhachHang(KhachHang instance);
    partial void InsertDoiTac(DoiTac instance);
    partial void UpdateDoiTac(DoiTac instance);
    partial void DeleteDoiTac(DoiTac instance);
    partial void InsertGiaoDich(GiaoDich instance);
    partial void UpdateGiaoDich(GiaoDich instance);
    partial void DeleteGiaoDich(GiaoDich instance);
    #endregion
		
		public ServiceDatabaseDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["BankServiceConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceDatabaseDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceDatabaseDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceDatabaseDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ServiceDatabaseDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<KhachHang> KhachHangs
		{
			get
			{
				return this.GetTable<KhachHang>();
			}
		}
		
		public System.Data.Linq.Table<DoiTac> DoiTacs
		{
			get
			{
				return this.GetTable<DoiTac>();
			}
		}
		
		public System.Data.Linq.Table<GiaoDich> GiaoDiches
		{
			get
			{
				return this.GetTable<GiaoDich>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maKH;
		
		private string _pin;
		
		private decimal _soDu;
		
		private EntitySet<GiaoDich> _GiaoDiches;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnpinChanging(string value);
    partial void OnpinChanged();
    partial void OnsoDuChanging(decimal value);
    partial void OnsoDuChanged();
    #endregion
		
		public KhachHang()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pin", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string pin
		{
			get
			{
				return this._pin;
			}
			set
			{
				if ((this._pin != value))
				{
					this.OnpinChanging(value);
					this.SendPropertyChanging();
					this._pin = value;
					this.SendPropertyChanged("pin");
					this.OnpinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDu")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal soDu
		{
			get
			{
				return this._soDu;
			}
			set
			{
				if ((this._soDu != value))
				{
					this.OnsoDuChanging(value);
					this.SendPropertyChanging();
					this._soDu = value;
					this.SendPropertyChanged("soDu");
					this.OnsoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GiaoDich", Storage="_GiaoDiches", ThisKey="maKH", OtherKey="maKH")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<GiaoDich> GiaoDiches
		{
			get
			{
				if ((this.serializing 
							&& (this._GiaoDiches.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._GiaoDiches;
			}
			set
			{
				this._GiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = this;
		}
		
		private void detach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.KhachHang = null;
		}
		
		private void Initialize()
		{
			this._GiaoDiches = new EntitySet<GiaoDich>(new Action<GiaoDich>(this.attach_GiaoDiches), new Action<GiaoDich>(this.detach_GiaoDiches));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class DoiTac : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maDoiTac;
		
		private string _matKhau;
		
		private decimal _soDu;
		
		private EntitySet<GiaoDich> _GiaoDiches;
		
		private bool serializing;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaDoiTacChanging(string value);
    partial void OnmaDoiTacChanged();
    partial void OnmatKhauChanging(string value);
    partial void OnmatKhauChanged();
    partial void OnsoDuChanging(decimal value);
    partial void OnsoDuChanged();
    #endregion
		
		public DoiTac()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoiTac", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string maDoiTac
		{
			get
			{
				return this._maDoiTac;
			}
			set
			{
				if ((this._maDoiTac != value))
				{
					this.OnmaDoiTacChanging(value);
					this.SendPropertyChanging();
					this._maDoiTac = value;
					this.SendPropertyChanged("maDoiTac");
					this.OnmaDoiTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matKhau", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string matKhau
		{
			get
			{
				return this._matKhau;
			}
			set
			{
				if ((this._matKhau != value))
				{
					this.OnmatKhauChanging(value);
					this.SendPropertyChanging();
					this._matKhau = value;
					this.SendPropertyChanged("matKhau");
					this.OnmatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soDu")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public decimal soDu
		{
			get
			{
				return this._soDu;
			}
			set
			{
				if ((this._soDu != value))
				{
					this.OnsoDuChanging(value);
					this.SendPropertyChanging();
					this._soDu = value;
					this.SendPropertyChanged("soDu");
					this.OnsoDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiTac_GiaoDich", Storage="_GiaoDiches", ThisKey="maDoiTac", OtherKey="maDoiTac")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4, EmitDefaultValue=false)]
		public EntitySet<GiaoDich> GiaoDiches
		{
			get
			{
				if ((this.serializing 
							&& (this._GiaoDiches.HasLoadedOrAssignedValues == false)))
				{
					return null;
				}
				return this._GiaoDiches;
			}
			set
			{
				this._GiaoDiches.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.DoiTac = this;
		}
		
		private void detach_GiaoDiches(GiaoDich entity)
		{
			this.SendPropertyChanging();
			entity.DoiTac = null;
		}
		
		private void Initialize()
		{
			this._GiaoDiches = new EntitySet<GiaoDich>(new Action<GiaoDich>(this.attach_GiaoDiches), new Action<GiaoDich>(this.detach_GiaoDiches));
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
		
		[global::System.Runtime.Serialization.OnSerializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerializing(StreamingContext context)
		{
			this.serializing = true;
		}
		
		[global::System.Runtime.Serialization.OnSerializedAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnSerialized(StreamingContext context)
		{
			this.serializing = false;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="")]
	[global::System.Runtime.Serialization.DataContractAttribute()]
	public partial class GiaoDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maGD;
		
		private string _maKH;
		
		private string _maDoiTac;
		
		private decimal _soTien;
		
		private string _tenGD;
		
		private int _loai;
		
		private System.DateTime _thoiGian;
		
		private decimal _phiGD;
		
		private EntityRef<KhachHang> _KhachHang;
		
		private EntityRef<DoiTac> _DoiTac;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaGDChanging(string value);
    partial void OnmaGDChanged();
    partial void OnmaKHChanging(string value);
    partial void OnmaKHChanged();
    partial void OnmaDoiTacChanging(string value);
    partial void OnmaDoiTacChanged();
    partial void OnsoTienChanging(decimal value);
    partial void OnsoTienChanged();
    partial void OntenGDChanging(string value);
    partial void OntenGDChanged();
    partial void OnloaiChanging(int value);
    partial void OnloaiChanged();
    partial void OnthoiGianChanging(System.DateTime value);
    partial void OnthoiGianChanged();
    partial void OnphiGDChanging(decimal value);
    partial void OnphiGDChanged();
    #endregion
		
		public GiaoDich()
		{
			this.Initialize();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maGD", CanBeNull=false, IsPrimaryKey=true)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=1)]
		public string maGD
		{
			get
			{
				return this._maGD;
			}
			set
			{
				if ((this._maGD != value))
				{
					this.OnmaGDChanging(value);
					this.SendPropertyChanging();
					this._maGD = value;
					this.SendPropertyChanged("maGD");
					this.OnmaGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maKH", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=2)]
		public string maKH
		{
			get
			{
				return this._maKH;
			}
			set
			{
				if ((this._maKH != value))
				{
					if (this._KhachHang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaKHChanging(value);
					this.SendPropertyChanging();
					this._maKH = value;
					this.SendPropertyChanged("maKH");
					this.OnmaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDoiTac", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=3)]
		public string maDoiTac
		{
			get
			{
				return this._maDoiTac;
			}
			set
			{
				if ((this._maDoiTac != value))
				{
					if (this._DoiTac.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaDoiTacChanging(value);
					this.SendPropertyChanging();
					this._maDoiTac = value;
					this.SendPropertyChanged("maDoiTac");
					this.OnmaDoiTacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soTien")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=4)]
		public decimal soTien
		{
			get
			{
				return this._soTien;
			}
			set
			{
				if ((this._soTien != value))
				{
					this.OnsoTienChanging(value);
					this.SendPropertyChanging();
					this._soTien = value;
					this.SendPropertyChanged("soTien");
					this.OnsoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenGD", CanBeNull=false)]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=5)]
		public string tenGD
		{
			get
			{
				return this._tenGD;
			}
			set
			{
				if ((this._tenGD != value))
				{
					this.OntenGDChanging(value);
					this.SendPropertyChanging();
					this._tenGD = value;
					this.SendPropertyChanged("tenGD");
					this.OntenGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loai")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=6)]
		public int loai
		{
			get
			{
				return this._loai;
			}
			set
			{
				if ((this._loai != value))
				{
					this.OnloaiChanging(value);
					this.SendPropertyChanging();
					this._loai = value;
					this.SendPropertyChanged("loai");
					this.OnloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGian")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=7)]
		public System.DateTime thoiGian
		{
			get
			{
				return this._thoiGian;
			}
			set
			{
				if ((this._thoiGian != value))
				{
					this.OnthoiGianChanging(value);
					this.SendPropertyChanging();
					this._thoiGian = value;
					this.SendPropertyChanged("thoiGian");
					this.OnthoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phiGD")]
		[global::System.Runtime.Serialization.DataMemberAttribute(Order=8)]
		public decimal phiGD
		{
			get
			{
				return this._phiGD;
			}
			set
			{
				if ((this._phiGD != value))
				{
					this.OnphiGDChanging(value);
					this.SendPropertyChanging();
					this._phiGD = value;
					this.SendPropertyChanged("phiGD");
					this.OnphiGDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KhachHang_GiaoDich", Storage="_KhachHang", ThisKey="maKH", OtherKey="maKH", IsForeignKey=true)]
		public KhachHang KhachHang
		{
			get
			{
				return this._KhachHang.Entity;
			}
			set
			{
				KhachHang previousValue = this._KhachHang.Entity;
				if (((previousValue != value) 
							|| (this._KhachHang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KhachHang.Entity = null;
						previousValue.GiaoDiches.Remove(this);
					}
					this._KhachHang.Entity = value;
					if ((value != null))
					{
						value.GiaoDiches.Add(this);
						this._maKH = value.maKH;
					}
					else
					{
						this._maKH = default(string);
					}
					this.SendPropertyChanged("KhachHang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DoiTac_GiaoDich", Storage="_DoiTac", ThisKey="maDoiTac", OtherKey="maDoiTac", IsForeignKey=true)]
		public DoiTac DoiTac
		{
			get
			{
				return this._DoiTac.Entity;
			}
			set
			{
				DoiTac previousValue = this._DoiTac.Entity;
				if (((previousValue != value) 
							|| (this._DoiTac.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DoiTac.Entity = null;
						previousValue.GiaoDiches.Remove(this);
					}
					this._DoiTac.Entity = value;
					if ((value != null))
					{
						value.GiaoDiches.Add(this);
						this._maDoiTac = value.maDoiTac;
					}
					else
					{
						this._maDoiTac = default(string);
					}
					this.SendPropertyChanged("DoiTac");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void Initialize()
		{
			this._KhachHang = default(EntityRef<KhachHang>);
			this._DoiTac = default(EntityRef<DoiTac>);
			OnCreated();
		}
		
		[global::System.Runtime.Serialization.OnDeserializingAttribute()]
		[global::System.ComponentModel.EditorBrowsableAttribute(EditorBrowsableState.Never)]
		public void OnDeserializing(StreamingContext context)
		{
			this.Initialize();
		}
	}
}
#pragma warning restore 1591
