//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElevationShop.ServiceReference2 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DoiTac", Namespace="http://schemas.datacontract.org/2004/07/WebService_ASM_TungBT")]
    [System.SerializableAttribute()]
    public partial class DoiTac : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maDoiTacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string matKhauField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal soDuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElevationShop.ServiceReference2.GiaoDich[] GiaoDichesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maDoiTac {
            get {
                return this.maDoiTacField;
            }
            set {
                if ((object.ReferenceEquals(this.maDoiTacField, value) != true)) {
                    this.maDoiTacField = value;
                    this.RaisePropertyChanged("maDoiTac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string matKhau {
            get {
                return this.matKhauField;
            }
            set {
                if ((object.ReferenceEquals(this.matKhauField, value) != true)) {
                    this.matKhauField = value;
                    this.RaisePropertyChanged("matKhau");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal soDu {
            get {
                return this.soDuField;
            }
            set {
                if ((this.soDuField.Equals(value) != true)) {
                    this.soDuField = value;
                    this.RaisePropertyChanged("soDu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ElevationShop.ServiceReference2.GiaoDich[] GiaoDiches {
            get {
                return this.GiaoDichesField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaoDichesField, value) != true)) {
                    this.GiaoDichesField = value;
                    this.RaisePropertyChanged("GiaoDiches");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GiaoDich", Namespace="http://schemas.datacontract.org/2004/07/WebService_ASM_TungBT")]
    [System.SerializableAttribute()]
    public partial class GiaoDich : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maDoiTacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal soTienField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string tenGDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int loaiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime thoiGianField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal phiGDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maGD {
            get {
                return this.maGDField;
            }
            set {
                if ((object.ReferenceEquals(this.maGDField, value) != true)) {
                    this.maGDField = value;
                    this.RaisePropertyChanged("maGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKH {
            get {
                return this.maKHField;
            }
            set {
                if ((object.ReferenceEquals(this.maKHField, value) != true)) {
                    this.maKHField = value;
                    this.RaisePropertyChanged("maKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string maDoiTac {
            get {
                return this.maDoiTacField;
            }
            set {
                if ((object.ReferenceEquals(this.maDoiTacField, value) != true)) {
                    this.maDoiTacField = value;
                    this.RaisePropertyChanged("maDoiTac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal soTien {
            get {
                return this.soTienField;
            }
            set {
                if ((this.soTienField.Equals(value) != true)) {
                    this.soTienField = value;
                    this.RaisePropertyChanged("soTien");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string tenGD {
            get {
                return this.tenGDField;
            }
            set {
                if ((object.ReferenceEquals(this.tenGDField, value) != true)) {
                    this.tenGDField = value;
                    this.RaisePropertyChanged("tenGD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int loai {
            get {
                return this.loaiField;
            }
            set {
                if ((this.loaiField.Equals(value) != true)) {
                    this.loaiField = value;
                    this.RaisePropertyChanged("loai");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime thoiGian {
            get {
                return this.thoiGianField;
            }
            set {
                if ((this.thoiGianField.Equals(value) != true)) {
                    this.thoiGianField = value;
                    this.RaisePropertyChanged("thoiGian");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public decimal phiGD {
            get {
                return this.phiGDField;
            }
            set {
                if ((this.phiGDField.Equals(value) != true)) {
                    this.phiGDField = value;
                    this.RaisePropertyChanged("phiGD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KhachHang", Namespace="http://schemas.datacontract.org/2004/07/WebService_ASM_TungBT")]
    [System.SerializableAttribute()]
    public partial class KhachHang : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string maKHField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string pinField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal soDuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ElevationShop.ServiceReference2.GiaoDich[] GiaoDichesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string maKH {
            get {
                return this.maKHField;
            }
            set {
                if ((object.ReferenceEquals(this.maKHField, value) != true)) {
                    this.maKHField = value;
                    this.RaisePropertyChanged("maKH");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pin {
            get {
                return this.pinField;
            }
            set {
                if ((object.ReferenceEquals(this.pinField, value) != true)) {
                    this.pinField = value;
                    this.RaisePropertyChanged("pin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal soDu {
            get {
                return this.soDuField;
            }
            set {
                if ((this.soDuField.Equals(value) != true)) {
                    this.soDuField = value;
                    this.RaisePropertyChanged("soDu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public ElevationShop.ServiceReference2.GiaoDich[] GiaoDiches {
            get {
                return this.GiaoDichesField;
            }
            set {
                if ((object.ReferenceEquals(this.GiaoDichesField, value) != true)) {
                    this.GiaoDichesField = value;
                    this.RaisePropertyChanged("GiaoDiches");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IBankingService")]
    public interface IBankingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/ThanhToan", ReplyAction="http://tempuri.org/IBankingService/ThanhToanResponse")]
        string ThanhToan(ElevationShop.ServiceReference2.DoiTac doiTac, ElevationShop.ServiceReference2.KhachHang khachHang, decimal soTien, int hthuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/ThanhToan", ReplyAction="http://tempuri.org/IBankingService/ThanhToanResponse")]
        System.Threading.Tasks.Task<string> ThanhToanAsync(ElevationShop.ServiceReference2.DoiTac doiTac, ElevationShop.ServiceReference2.KhachHang khachHang, decimal soTien, int hthuc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/LichSuKhachHang", ReplyAction="http://tempuri.org/IBankingService/LichSuKhachHangResponse")]
        ElevationShop.ServiceReference2.GiaoDich[] LichSuKhachHang(ElevationShop.ServiceReference2.KhachHang khachHang, System.DateTime fromDate, System.DateTime todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/LichSuKhachHang", ReplyAction="http://tempuri.org/IBankingService/LichSuKhachHangResponse")]
        System.Threading.Tasks.Task<ElevationShop.ServiceReference2.GiaoDich[]> LichSuKhachHangAsync(ElevationShop.ServiceReference2.KhachHang khachHang, System.DateTime fromDate, System.DateTime todate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/LichSuDoiTac", ReplyAction="http://tempuri.org/IBankingService/LichSuDoiTacResponse")]
        ElevationShop.ServiceReference2.GiaoDich[] LichSuDoiTac(ElevationShop.ServiceReference2.DoiTac doiTac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/LichSuDoiTac", ReplyAction="http://tempuri.org/IBankingService/LichSuDoiTacResponse")]
        System.Threading.Tasks.Task<ElevationShop.ServiceReference2.GiaoDich[]> LichSuDoiTacAsync(ElevationShop.ServiceReference2.DoiTac doiTac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/getSoDuKhachHang", ReplyAction="http://tempuri.org/IBankingService/getSoDuKhachHangResponse")]
        decimal getSoDuKhachHang(ElevationShop.ServiceReference2.KhachHang khachHang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/getSoDuKhachHang", ReplyAction="http://tempuri.org/IBankingService/getSoDuKhachHangResponse")]
        System.Threading.Tasks.Task<decimal> getSoDuKhachHangAsync(ElevationShop.ServiceReference2.KhachHang khachHang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/getSoDuDoiTac", ReplyAction="http://tempuri.org/IBankingService/getSoDuDoiTacResponse")]
        decimal getSoDuDoiTac(ElevationShop.ServiceReference2.DoiTac doiTac);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBankingService/getSoDuDoiTac", ReplyAction="http://tempuri.org/IBankingService/getSoDuDoiTacResponse")]
        System.Threading.Tasks.Task<decimal> getSoDuDoiTacAsync(ElevationShop.ServiceReference2.DoiTac doiTac);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBankingServiceChannel : ElevationShop.ServiceReference2.IBankingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BankingServiceClient : System.ServiceModel.ClientBase<ElevationShop.ServiceReference2.IBankingService>, ElevationShop.ServiceReference2.IBankingService {
        
        public BankingServiceClient() {
        }
        
        public BankingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BankingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ThanhToan(ElevationShop.ServiceReference2.DoiTac doiTac, ElevationShop.ServiceReference2.KhachHang khachHang, decimal soTien, int hthuc) {
            return base.Channel.ThanhToan(doiTac, khachHang, soTien, hthuc);
        }
        
        public System.Threading.Tasks.Task<string> ThanhToanAsync(ElevationShop.ServiceReference2.DoiTac doiTac, ElevationShop.ServiceReference2.KhachHang khachHang, decimal soTien, int hthuc) {
            return base.Channel.ThanhToanAsync(doiTac, khachHang, soTien, hthuc);
        }
        
        public ElevationShop.ServiceReference2.GiaoDich[] LichSuKhachHang(ElevationShop.ServiceReference2.KhachHang khachHang, System.DateTime fromDate, System.DateTime todate) {
            return base.Channel.LichSuKhachHang(khachHang, fromDate, todate);
        }
        
        public System.Threading.Tasks.Task<ElevationShop.ServiceReference2.GiaoDich[]> LichSuKhachHangAsync(ElevationShop.ServiceReference2.KhachHang khachHang, System.DateTime fromDate, System.DateTime todate) {
            return base.Channel.LichSuKhachHangAsync(khachHang, fromDate, todate);
        }
        
        public ElevationShop.ServiceReference2.GiaoDich[] LichSuDoiTac(ElevationShop.ServiceReference2.DoiTac doiTac) {
            return base.Channel.LichSuDoiTac(doiTac);
        }
        
        public System.Threading.Tasks.Task<ElevationShop.ServiceReference2.GiaoDich[]> LichSuDoiTacAsync(ElevationShop.ServiceReference2.DoiTac doiTac) {
            return base.Channel.LichSuDoiTacAsync(doiTac);
        }
        
        public decimal getSoDuKhachHang(ElevationShop.ServiceReference2.KhachHang khachHang) {
            return base.Channel.getSoDuKhachHang(khachHang);
        }
        
        public System.Threading.Tasks.Task<decimal> getSoDuKhachHangAsync(ElevationShop.ServiceReference2.KhachHang khachHang) {
            return base.Channel.getSoDuKhachHangAsync(khachHang);
        }
        
        public decimal getSoDuDoiTac(ElevationShop.ServiceReference2.DoiTac doiTac) {
            return base.Channel.getSoDuDoiTac(doiTac);
        }
        
        public System.Threading.Tasks.Task<decimal> getSoDuDoiTacAsync(ElevationShop.ServiceReference2.DoiTac doiTac) {
            return base.Channel.getSoDuDoiTacAsync(doiTac);
        }
    }
}
