//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int BookIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ISBNField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ISBN {
            get {
                return this.ISBNField;
            }
            set {
                if ((object.ReferenceEquals(this.ISBNField, value) != true)) {
                    this.ISBNField = value;
                    this.RaisePropertyChanged("ISBN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBook.BookServiceSoap")]
    public interface BookServiceSoap {
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse AddBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBook", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse> AddBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBook", ReplyAction="*")]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse DeleteBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBook", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse> DeleteBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookById", ReplyAction="*")]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse GetBookById(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookById", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse> GetBookByIdAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest request);
        
        // CODEGEN: Generating message contract since element name GetBookListResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookList", ReplyAction="*")]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse GetBookList(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBookList", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse> GetBookListAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest request);
        
        // CODEGEN: Generating message contract since element name book from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBook", ReplyAction="*")]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse UpdateBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBook", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse> UpdateBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBook", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequestBody Body;
        
        public AddBookRequest() {
        }
        
        public AddBookRequest(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book;
        
        public AddBookRequestBody() {
        }
        
        public AddBookRequestBody(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponseBody Body;
        
        public AddBookResponse() {
        }
        
        public AddBookResponse(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddBookResult;
        
        public AddBookResponseBody() {
        }
        
        public AddBookResponseBody(string AddBookResult) {
            this.AddBookResult = AddBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBook", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequestBody Body;
        
        public DeleteBookRequest() {
        }
        
        public DeleteBookRequest(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public DeleteBookRequestBody() {
        }
        
        public DeleteBookRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponseBody Body;
        
        public DeleteBookResponse() {
        }
        
        public DeleteBookResponse(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteBookResult;
        
        public DeleteBookResponseBody() {
        }
        
        public DeleteBookResponseBody(string DeleteBookResult) {
            this.DeleteBookResult = DeleteBookResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookById", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequestBody Body;
        
        public GetBookByIdRequest() {
        }
        
        public GetBookByIdRequest(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public GetBookByIdRequestBody() {
        }
        
        public GetBookByIdRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponseBody Body;
        
        public GetBookByIdResponse() {
        }
        
        public GetBookByIdResponse(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book GetBookByIdResult;
        
        public GetBookByIdResponseBody() {
        }
        
        public GetBookByIdResponseBody(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book GetBookByIdResult) {
            this.GetBookByIdResult = GetBookByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookList", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequestBody Body;
        
        public GetBookListRequest() {
        }
        
        public GetBookListRequest(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetBookListRequestBody {
        
        public GetBookListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookListResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponseBody Body;
        
        public GetBookListResponse() {
        }
        
        public GetBookListResponse(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetBookListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book[] GetBookListResult;
        
        public GetBookListResponseBody() {
        }
        
        public GetBookListResponseBody(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book[] GetBookListResult) {
            this.GetBookListResult = GetBookListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBook", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequestBody Body;
        
        public UpdateBookRequest() {
        }
        
        public UpdateBookRequest(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book;
        
        public UpdateBookRequestBody() {
        }
        
        public UpdateBookRequestBody(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            this.book = book;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponseBody Body;
        
        public UpdateBookResponse() {
        }
        
        public UpdateBookResponse(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBookResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateBookResult;
        
        public UpdateBookResponseBody() {
        }
        
        public UpdateBookResponseBody(string UpdateBookResult) {
            this.UpdateBookResult = UpdateBookResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BookServiceSoapChannel : ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BookServiceSoapClient : System.ServiceModel.ClientBase<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap>, ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap {
        
        public BookServiceSoapClient() {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.AddBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest request) {
            return base.Channel.AddBook(request);
        }
        
        public string AddBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequestBody();
            inValue.Body.book = book;
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse retVal = ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).AddBook(inValue);
            return retVal.Body.AddBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse> ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.AddBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest request) {
            return base.Channel.AddBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookResponse> AddBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.AddBookRequestBody();
            inValue.Body.book = book;
            return ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).AddBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.DeleteBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest request) {
            return base.Channel.DeleteBook(request);
        }
        
        public string DeleteBook(string id) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequestBody();
            inValue.Body.id = id;
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse retVal = ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).DeleteBook(inValue);
            return retVal.Body.DeleteBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse> ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.DeleteBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest request) {
            return base.Channel.DeleteBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookResponse> DeleteBookAsync(string id) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.DeleteBookRequestBody();
            inValue.Body.id = id;
            return ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).DeleteBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.GetBookById(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest request) {
            return base.Channel.GetBookById(request);
        }
        
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book GetBookById(string id) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequestBody();
            inValue.Body.id = id;
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse retVal = ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).GetBookById(inValue);
            return retVal.Body.GetBookByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse> ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.GetBookByIdAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest request) {
            return base.Channel.GetBookByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdResponse> GetBookByIdAsync(string id) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookByIdRequestBody();
            inValue.Body.id = id;
            return ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).GetBookByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.GetBookList(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest request) {
            return base.Channel.GetBookList(request);
        }
        
        public ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book[] GetBookList() {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequestBody();
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse retVal = ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).GetBookList(inValue);
            return retVal.Body.GetBookListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse> ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.GetBookListAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest request) {
            return base.Channel.GetBookListAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListResponse> GetBookListAsync() {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.GetBookListRequestBody();
            return ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).GetBookListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.UpdateBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest request) {
            return base.Channel.UpdateBook(request);
        }
        
        public string UpdateBook(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequestBody();
            inValue.Body.book = book;
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse retVal = ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).UpdateBook(inValue);
            return retVal.Body.UpdateBookResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse> ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap.UpdateBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest request) {
            return base.Channel.UpdateBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookResponse> UpdateBookAsync(ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.Book book) {
            ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest inValue = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequest();
            inValue.Body = new ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.UpdateBookRequestBody();
            inValue.Body.book = book;
            return ((ConsumingSOAPServiceCRUD_Client.ServiceReferenceBook.BookServiceSoap)(this)).UpdateBookAsync(inValue);
        }
    }
}
